function initialize() {
	
	var towns = [ 
		{ name: "Acton", id: "Acton" },
		{ name: "Arlington", id: "Arlington" },
		{ name: "Ashland", id: "Ashland" },
		{ name: "Bedford", id: "Bedford" },
		{ name: "Bellingham", id: "Bellingham" },
		{ name: "Belmont", id: "Belmont" },
		{ name: "Beverly", id: "Beverly" },
		{ name: "Bolton", id: "Bolton" },
		{ name: "Boston", id: "Boston" },
		{ name: "Boxborough", id: "Boxborough" },
		{ name: "Braintree", id: "Braintree" },
		{ name: "Brookline", id: "Brookline" },
		{ name: "Burlington", id: "Burlington" },
		{ name: "Cambridge", id: "Cambridge" },
		{ name: "Canton", id: "Canton" },
		{ name: "Carlisle", id: "Carlisle" },
		{ name: "Chelsea", id: "Chelsea" },
		{ name: "Cohasset", id: "Cohasset" },
		{ name: "Concord", id: "Concord" },
		{ name: "Danvers", id: "Danvers" },
		{ name: "Dedham", id: "Dedham" },
		{ name: "Dover", id: "Dover" },
		{ name: "Essex", id: "Essex" },
		{ name: "Everett", id: "Everett" },
		{ name: "Foxborough", id: "Foxborough" },
		{ name: "Framingham", id: "Framingham" },
		{ name: "Franklin", id: "Franklin" },
		{ name: "Gloucester", id: "Gloucester" },
		{ name: "Hamilton", id: "Hamilton" },
		{ name: "Hingham", id: "Hingham" },
		{ name: "Holbrook", id: "Holbrook" },
		{ name: "Holliston", id: "Holliston" },
		{ name: "Hopkinton", id: "Hopkinton" },
		{ name: "Hudson", id: "Hudson" },
		{ name: "Hull", id: "Hull" },
		{ name: "Ipswich", id: "Ipswich" },
		{ name: "Lexington", id: "Lexington" },
		{ name: "Lincoln", id: "Lincoln" },
		{ name: "Littleton", id: "Littleton" },
		{ name: "Lynn", id: "Lynn" },
		{ name: "Lynnfield", id: "Lynnfield" },
		{ name: "Malden", id: "Malden" },
		{ name: "Manchester", id: "Manchester" },
		{ name: "Marblehead", id: "Marblehead" },
		{ name: "Marlborough", id: "Marlborough" },
		{ name: "Marshfield", id: "Marshfield" },
		{ name: "Maynard", id: "Maynard" },
		{ name: "Medfield", id: "Medfield" },
		{ name: "Medford", id: "Medford" },
		{ name: "Medway", id: "Medway" },
		{ name: "Melrose", id: "Melrose" },
		{ name: "Middleton", id: "Middleton" },
		{ name: "Milford", id: "Milford" },
		{ name: "Millis", id: "Millis" },
		{ name: "Milton", id: "Milton" },
		{ name: "Nahant", id: "Nahant" },
		{ name: "Natick", id: "Natick" },
		{ name: "Needham", id: "Needham" },
		{ name: "Newton", id: "Newton" },
		{ name: "Norfolk", id: "Norfolk" },
		{ name: "North Reading", id: "North Reading" },
		{ name: "Norwell", id: "Norwell" },
		{ name: "Norwood", id: "Norwood" },
		{ name: "Peabody", id: "Peabody" },
		{ name: "Quincy", id: "Quincy" },
		{ name: "Randolph", id: "Randolph" },
		{ name: "Reading", id: "Reading" },
		{ name: "Revere", id: "Revere" },
		{ name: "Rockland", id: "Rockland" },
		{ name: "Rockport", id: "Rockport" },
		{ name: "Salem", id: "Salem" },
		{ name: "Saugus", id: "Saugus" },
		{ name: "Scituate", id: "Scituate" },
		{ name: "Sharon", id: "Sharon" },
		{ name: "Sherborn", id: "Sherborn" },
		{ name: "Somerville", id: "Somerville" },
		{ name: "Southborough", id: "Southborough" },
		{ name: "Stoneham", id: "Stoneham" },
		{ name: "Stow", id: "Stow" },
		{ name: "Sudbury", id: "Sudbury" },
		{ name: "Swampscott", id: "Swampscott" },
		{ name: "Topsfield", id: "Topsfield" },
		{ name: "Wakefield", id: "Wakefield" },
		{ name: "Walpole", id: "Walpole" },
		{ name: "Waltham", id: "Waltham" },
		{ name: "Watertown", id: "Watertown" },
		{ name: "Wayland", id: "Wayland" },
		{ name: "Wellesley", id: "Wellesley" },
		{ name: "Wenham", id: "Wenham" },
		{ name: "Weston", id: "Weston" },
		{ name: "Westwood", id: "Westwood" },
		{ name: "Weymouth", id: "Weymouth" },
		{ name: "Wilmington", id: "Wilmington" },
		{ name: "Winchester", id: "Winchester" },
		{ name: "Winthrop", id: "Winthrop" },
		{ name: "Woburn", id: "Woburn" },
		{ name: "Wrentham", id: "Wrentham" }
	];

    var sky = [
		{ name: "No Data", id: 99 },
        { name: "Suuny", id: 1 },
        { name: "Partly Cloudy", id: 2 },
        { name: "Overcast", id: 3 },
        { name: "Precipitation", id: 4 }
    ];
	
	
	// Setup grid for input of count data
	
	var columns = [
		{ title: "time" }, 
		{ title: "bike" },
		{ title: "ped" },
		{ title: "child" },
		{ title: "jogger" },
		{ title: "skater" },
		{ title: "wheelchair" }
	];
	
var initialData = [
		// [ " 6:00 am",  0,  0, 0, 0, 0, 0 ],
		// [ " 6:15 am",  0,  0, 0, 0, 0, 0 ],
		[ " 6:30 am",  0,  0, 0, 0, 0, 0 ],
		[ " 6:45 am",  0,  0, 0, 0, 0, 0 ],
		[ " 7:00 am",  0,  0, 0, 0, 0, 0 ],
		[ " 7:15 am",  0,  0, 0, 0, 0, 0 ],
		[ " 7:30 am",  0,  0, 0, 0, 0, 0 ],
		[ " 7:45 am",  0,  0, 0, 0, 0, 0 ],
		[ " 8:00 am",  0,  0, 0, 0, 0, 0 ],
		[ " 8:15 am",  0,  0, 0, 0, 0, 0 ],
		[ " 8:30 am",  0,  0, 0, 0, 0, 0 ],
		[ " 8:45 am",  0,  0, 0, 0, 0, 0 ],
		[ " 9:00 am",  0,  0, 0, 0, 0, 0 ],
		[ " 9:15 am",  0,  0, 0, 0, 0, 0 ],
		[ " 9:30 am",  0,  0, 0, 0, 0, 0 ],
		[ " 9:45 am",  0,  0, 0, 0, 0, 0 ],
		[ "10:00 am",  0,  0, 0, 0, 0, 0 ],
		[ "10:15 am",  0,  0, 0, 0, 0, 0 ],
		[ "10:30 am",  0,  0, 0, 0, 0, 0 ],
		[ "10:45 am",  0,  0, 0, 0, 0, 0 ],
		[ "11:00 am",  0,  0, 0, 0, 0, 0 ],
		[ "11:15 am",  0,  0, 0, 0, 0, 0 ],
		[ "11:30 am",  0,  0, 0, 0, 0, 0 ],
		[ "11:45 am",  0,  0, 0, 0, 0, 0 ],
		[ "12:00 pm",  0,  0, 0, 0, 0, 0 ],
		[ "12:15 pm",  0,  0, 0, 0, 0, 0 ],
		[ "12:30 pm",  0,  0, 0, 0, 0, 0 ],
		[ "12:45 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 1:00 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 1:15 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 1:30 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 1:45 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 2:00 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 2:15 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 2:30 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 2:45 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 3:00 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 3:15 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 3:30 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 3:45 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 4:00 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 4:15 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 4:30 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 4:45 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 5:00 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 5:15 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 5:30 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 5:45 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 6:00 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 6:15 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 6:30 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 6:45 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 7:00 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 7:15 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 7:30 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 7:45 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 8:00 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 8:15 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 8:30 pm",  0,  0, 0, 0, 0, 0 ],
		[ " 8:45 pm",  0,  0, 0, 0, 0, 0 ],
	];


	
    var inputTable = new DataTable('#myTable', { columns: columns, data: initialData });


} // initialize
