function initialize() {
	
	var towns = [ 
		{ name: "Acton", id: "Acton" },
		{ name: "Arlington", id: "Arlington" },
		{ name: "Ashland", id: "Ashland" },
		{ name: "Bedford", id: "Bedford" },
		{ name: "Bellingham", id: "Bellingham" },
		{ name: "Belmont", id: "Belmont" },
		{ name: "Beverly", id: "Beverly" },
		{ name: "Bolton", id: "Bolton" },
		{ name: "Boston", id: "Boston" },
		{ name: "Boxborough", id: "Boxborough" },
		{ name: "Braintree", id: "Braintree" },
		{ name: "Brookline", id: "Brookline" },
		{ name: "Burlington", id: "Burlington" },
		{ name: "Cambridge", id: "Cambridge" },
		{ name: "Canton", id: "Canton" },
		{ name: "Carlisle", id: "Carlisle" },
		{ name: "Chelsea", id: "Chelsea" },
		{ name: "Cohasset", id: "Cohasset" },
		{ name: "Concord", id: "Concord" },
		{ name: "Danvers", id: "Danvers" },
		{ name: "Dedham", id: "Dedham" },
		{ name: "Dover", id: "Dover" },
		{ name: "Essex", id: "Essex" },
		{ name: "Everett", id: "Everett" },
		{ name: "Foxborough", id: "Foxborough" },
		{ name: "Framingham", id: "Framingham" },
		{ name: "Franklin", id: "Franklin" },
		{ name: "Gloucester", id: "Gloucester" },
		{ name: "Hamilton", id: "Hamilton" },
		{ name: "Hingham", id: "Hingham" },
		{ name: "Holbrook", id: "Holbrook" },
		{ name: "Holliston", id: "Holliston" },
		{ name: "Hopkinton", id: "Hopkinton" },
		{ name: "Hudson", id: "Hudson" },
		{ name: "Hull", id: "Hull" },
		{ name: "Ipswich", id: "Ipswich" },
		{ name: "Lexington", id: "Lexington" },
		{ name: "Lincoln", id: "Lincoln" },
		{ name: "Littleton", id: "Littleton" },
		{ name: "Lynn", id: "Lynn" },
		{ name: "Lynnfield", id: "Lynnfield" },
		{ name: "Malden", id: "Malden" },
		{ name: "Manchester", id: "Manchester" },
		{ name: "Marblehead", id: "Marblehead" },
		{ name: "Marlborough", id: "Marlborough" },
		{ name: "Marshfield", id: "Marshfield" },
		{ name: "Maynard", id: "Maynard" },
		{ name: "Medfield", id: "Medfield" },
		{ name: "Medford", id: "Medford" },
		{ name: "Medway", id: "Medway" },
		{ name: "Melrose", id: "Melrose" },
		{ name: "Middleton", id: "Middleton" },
		{ name: "Milford", id: "Milford" },
		{ name: "Millis", id: "Millis" },
		{ name: "Milton", id: "Milton" },
		{ name: "Nahant", id: "Nahant" },
		{ name: "Natick", id: "Natick" },
		{ name: "Needham", id: "Needham" },
		{ name: "Newton", id: "Newton" },
		{ name: "Norfolk", id: "Norfolk" },
		{ name: "North Reading", id: "North Reading" },
		{ name: "Norwell", id: "Norwell" },
		{ name: "Norwood", id: "Norwood" },
		{ name: "Peabody", id: "Peabody" },
		{ name: "Quincy", id: "Quincy" },
		{ name: "Randolph", id: "Randolph" },
		{ name: "Reading", id: "Reading" },
		{ name: "Revere", id: "Revere" },
		{ name: "Rockland", id: "Rockland" },
		{ name: "Rockport", id: "Rockport" },
		{ name: "Salem", id: "Salem" },
		{ name: "Saugus", id: "Saugus" },
		{ name: "Scituate", id: "Scituate" },
		{ name: "Sharon", id: "Sharon" },
		{ name: "Sherborn", id: "Sherborn" },
		{ name: "Somerville", id: "Somerville" },
		{ name: "Southborough", id: "Southborough" },
		{ name: "Stoneham", id: "Stoneham" },
		{ name: "Stow", id: "Stow" },
		{ name: "Sudbury", id: "Sudbury" },
		{ name: "Swampscott", id: "Swampscott" },
		{ name: "Topsfield", id: "Topsfield" },
		{ name: "Wakefield", id: "Wakefield" },
		{ name: "Walpole", id: "Walpole" },
		{ name: "Waltham", id: "Waltham" },
		{ name: "Watertown", id: "Watertown" },
		{ name: "Wayland", id: "Wayland" },
		{ name: "Wellesley", id: "Wellesley" },
		{ name: "Wenham", id: "Wenham" },
		{ name: "Weston", id: "Weston" },
		{ name: "Westwood", id: "Westwood" },
		{ name: "Weymouth", id: "Weymouth" },
		{ name: "Wilmington", id: "Wilmington" },
		{ name: "Winchester", id: "Winchester" },
		{ name: "Winthrop", id: "Winthrop" },
		{ name: "Woburn", id: "Woburn" },
		{ name: "Wrentham", id: "Wrentham" }
	];

    var sky = [
		{ name: "No Data", id: 99 },
        { name: "Suuny", id: 1 },
        { name: "Partly Cloudy", id: 2 },
        { name: "Overcast", id: 3 },
        { name: "Precipitation", id: 4 }
    ];
	
	
	// Setup grid for input of count data
	
	var columns = [
		{ title: "Time", name: "time", type: "text", inserting: false, filtering: false, editing: false, sorting: false}, 
		{ title: "Bicyclist", name: "bike", type: "number", inserting: true, filtering: false, editing: true, sorting: false  },
		{ title: "Pedestrian / Walker", name: "ped", type: "number", inserting: true, filtering: false, editing: true, sorting: false },
		{ title: "Child in carrier", name : "child", type: "number", inserting: true, filtering: false, editing: true, sorting: false },
		{ title: "Jogger", name: "jogger", type: "number", inserting: true, filtering: false, editing: true, sorting: false },
		{ title: "Roller Blader / Skater" , name: "skater", type: "number", inserting: true, filtering: false, editing: true, sorting: false },
		{ title: "Wheelchair User", name: "wheelchair", type: "number", inserting: true, filtering: false, editing: true, sorting: false }
	];
	
	var empty_data = [
		{ time : " 6:00 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 }, // For the sake of symmetry
		{ time : " 6:15 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 }, // For the sake of symmetry
		{ time : " 6:30 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 6:45 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 7:00 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 7:15 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 7:30 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 7:45 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 8:00 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 8:15 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 8:30 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 8:45 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 9:00 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 9:15 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 9:30 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 9:45 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : "10:00 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : "10:15 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : "10:30 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : "10:45 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : "11:00 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : "11:15 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : "11:30 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : "11:45 am", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : "12:00 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : "12:15 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : "12:30 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : "12:45 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 1:00 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 1:15 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 1:30 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 1:45 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 2:00 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 2:15 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 2:30 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 2:45 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 3:00 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 3:15 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 3:30 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 3:45 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 4:00 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 4:15 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 4:30 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 4:45 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 5:00 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 5:15 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 5:30 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 5:45 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 6:00 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 6:15 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 6:30 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 6:45 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 7:00 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 7:15 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 7:30 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 7:45 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 8:00 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 8:15 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 8:30 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
		{ time : " 8:45 pm", "bike" : 0, "ped" : 0, "child" : 0, "jogger" : 0, "skater" : 0, "wheelchair" : 0 },
	];
	

	// Minimal "hello, world" test
	var grid = new gridjs.Grid({
	  columns: ["Name", "Email", "Phone Number"],
	  data: [
		["John", "john@example.com", "(353) 01 222 3333"],
		["Mark", "mark@gmail.com", "(01) 22 888 4444"],
		["Eoin", "eoin@gmail.com", "0097 22 654 00033"],
		["Sarah", "sarahcdd@gmail.com", "+322 876 1233"],
		["Afshin", "afshin@mail.com", "(353) 22 87 8356"]
	  ]
	}).render(document.getElementById("wrapper"));
} // initialize